name        : python3
version     : 3.5.1
release     : 7
source     :
    - https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz : c6d57c0c366d9060ab6c0cdf889ebf3d92711d466cc0119c441dbf2746f725c9
license     :
    - Python-2.0
summary     : Python development environment - 3.3.2
description : |
    The Python 3 package contains the Python development environment. This is useful for object-oriented programming, writing scripts, prototyping large programs or developing entire applications.
builddeps  :
    - pkgconfig(zlib)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - db5-devel
replaces   :
    - python3-setuptools
setup      : |
    %configure --prefix=/usr \
               --enable-shared \
               --with-system-expat \
               --with-system-ffi
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/bin/2to3
