name        : python3
version     : 3.4.3
release     : 5
source      :
    - https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tar.xz : b5b3963533768d5fc325a4d7a6bd6f666726002d696f1d399ec06b043ea996b8
license     :
    - Python-2.0
summary     : Python development environment - 3.3.2
description : |
    The Python 3 package contains the Python development environment. This is useful for object-oriented programming, writing scripts, prototyping large programs or developing entire applications.
builddeps  :
    - pkgconfig(zlib)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - db5-devel
setup      : |
    %configure --prefix=/usr \
               --enable-shared \
               --with-system-expat \
               --with-system-ffi
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/bin/2to3
