name       : python3
version    : 3.7.11
release    : 32
source     :
    - https://www.python.org/ftp/python/3.7.11/Python-3.7.11.tar.xz : ddb4196ab5c4f69e895920a422cb60d42b46e2de2b173ce7fd57f1435459a734
    - https://files.pythonhosted.org/packages/47/ca/f0d790b6e18b3a6f3bd5e80c2ee4edbb5807286c21cdd0862ca933f751dd/pip-21.1.3-py3-none-any.whl : 78cb760711fedc073246543801c84dc5377affead832e103ad0211f99303a204
license    : Python-2.0
summary    :
    - Python development environment - 3.7
    - test : Python 3.7 Test package
component  :
    - programming.python
    - test : programming.python
    - tkinter : programming.python
description: |
    The Python 3 package contains the Python development environment. This is useful for object-oriented programming, writing scripts, prototyping large programs or developing entire applications.
optimize   :
    - speed
networking : yes
builddeps  :
    - pkgconfig(harfbuzz) # Fix linking for tkinter
    - pkgconfig(libffi)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - bzip2-devel
    - db5-devel
    - gdbm-devel
replaces   :
    - python3-setuptools
rundeps    :
    - test : python3
    - tkinter : python3
patterns   :
    - /usr/include/python3.7m/pyconfig.h
    - test :
        - /usr/lib/python3.7/test
    - tkinter :
        - /usr/lib64/python3.7/lib-dynload/_tkinter.cpython-37m-x86_64-linux-gnu.so
setup      : |
    %apply_patches

    # Upgrade bundled pip
    sed -i 's/_PIP_VERSION = "20.1.1"/_PIP_VERSION = "21.1.3"/' Lib/ensurepip/__init__.py
    sed -i 's/_PIP_VERSION, "py2.py3"/_PIP_VERSION, "py3"/' Lib/ensurepip/__init__.py
    rm Lib/ensurepip/_bundled/pip-20.1.1-py2.py3-none-any.whl
    cp $sources/pip-21.1.3-py3-none-any.whl Lib/ensurepip/_bundled/

    %configure --enable-ipv6=yes \
               --enable-loadable-sqlite-extensions \
               --enable-optimizations \
               --enable-shared \
               --with-ensurepip=install \
               --with-system-expat \
               --with-system-ffi \
               --without-cxx-main \
               CFLAGS="$CFLAGS -I/usr/include"
build      : |
    %make
    # Note that during tests we will have an error on test_ssl. This is resolved in python 3.8 / 3.9.
    # See https://bugs.python.org/issue37322
    # https://github.com/python/cpython/commit/4c403b8ca2d0ef44b691cceaeeac9e110fd3f05a
install    : |
    %make_install
    rm $installdir/usr/bin/2to3
