name       : python3
version    : 3.7.7
release    : 27
source     :
    - https://www.python.org/ftp/python/3.7.7/Python-3.7.7.tar.xz : 06a0a9f1bf0d8cd1e4121194d666c4e28ddae4dd54346de6c343206599f02136
license    : Python-2.0
summary    :
    - Python development environment - 3.7
    - test : Python 3.7 Test package
component  :
    - programming.python
    - test : programming.python
    - tkinter : programming.python
description: |
    The Python 3 package contains the Python development environment. This is useful for object-oriented programming, writing scripts, prototyping large programs or developing entire applications.
optimize   :
    - speed
networking : yes
builddeps  :
    - pkgconfig(harfbuzz) # Fix linking for tkinter
    - pkgconfig(libffi)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - bzip2-devel
    - db5-devel
    - gdbm-devel
replaces   :
    - python3-setuptools
rundeps    :
    - test : python3
    - tkinter : python3
patterns   :
    - /usr/include/python3.7m/pyconfig.h
    - test :
        - /usr/lib/python3.7/test
    - tkinter :
        - /usr/lib64/python3.7/lib-dynload/_tkinter.cpython-37m-x86_64-linux-gnu.so
setup      : |
    %patch -p1 < $pkgfiles/0001-ensurepip-Always-install-pip-setuptools-ignoring-ins.patch

    %configure --enable-shared \
               --enable-optimizations \
               --with-system-expat \
               --with-system-ffi \
               --with-ensurepip=install \
               --without-cxx-main \
               --enable-ipv6=yes \
               --enable-loadable-sqlite-extensions \
               CFLAGS="$CFLAGS -I/usr/include"
build      : |
    %make profile-opt
    # Note that during tests we will have an error on test_ssl. This is resolved in python 3.8 / 3.9.
    # See https://bugs.python.org/issue37322
    # https://github.com/python/cpython/commit/4c403b8ca2d0ef44b691cceaeeac9e110fd3f05a
install    : |
    %make_install
    rm $installdir/usr/bin/2to3
