name       : python3
version    : 3.6.7
release    : 20
source     :
    - https://www.python.org/ftp/python/3.6.7/Python-3.6.7.tar.xz : 81fd1401a9d66533b0a3e9e3f4ea1c7c6702d57d5b90d659f971e6f1b745f77d
license    : Python-2.0
summary    :
    - Python development environment - 3.6
    - test : Python 3.6 Test package
component  :
    - programming.python
    - test : programming.python
    - tkinter : programming.python
description: |
    The Python 3 package contains the Python development environment. This is useful for object-oriented programming, writing scripts, prototyping large programs or developing entire applications.
builddeps  :
    - pkgconfig(harfbuzz) # Fix linking for tkinter
    - pkgconfig(libffi)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - pkgconfig(zlib)
    - bzip2-devel
    - db5-devel
    - gdbm-devel
replaces   :
    - python3-setuptools
rundeps    :
    - test : python3
    - tkinter : python3
patterns   :
    - /usr/include/python3.6m/pyconfig.h
    - test :
        - /usr/lib/python3.6/test
    - tkinter :
        - /usr/lib64/python3.6/lib-dynload/_tkinter.cpython-36m-x86_64-linux-gnu.so
setup      : |
    %patch -p1 < $pkgfiles/0001-ensurepip-Always-install-pip-setuptools-ignoring-ins.patch

    %configure --enable-shared \
               --with-system-expat \
               --with-system-ffi \
               --with-threads \
               --with-ensurepip=install \
               --without-cxx-main \
               --with-signal-module \
               --enable-ipv6=yes \
               --enable-loadable-sqlite-extensions \
               CFLAGS="$CFLAGS -I/usr/include"
build      : |
    %make profile-opt
install    : |
    %make_install
    rm $installdir/usr/bin/2to3
