name       : python3
version    : 3.10.9
release    : 52
source     :
    - https://www.python.org/ftp/python/3.10.9/Python-3.10.9.tar.xz : 5ae03e308260164baba39921fdb4dbf8e6d03d8235a939d4582b33f0b5e46a83
license    : Python-2.0
summary    :
    - Python development environment - 3.10
    - test : Python 3.10 Test package
component  :
    - programming.python
    - test : programming.python
    - tkinter : programming.python
description: |
    The Python 3 package contains the Python development environment. This is useful for object-oriented programming, writing scripts, prototyping large programs or developing entire applications.
optimize   :
    - speed
networking : yes
builddeps  :
    - pkgconfig(harfbuzz) # Fix linking for tkinter
    - pkgconfig(libffi)
    - pkgconfig(libxcrypt)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - bzip2-devel
    - db5-devel
    - gdbm-devel
replaces   :
    - python3-setuptools
rundeps    :
    - test : python3
    - tkinter : python3
patterns   :
    - /usr/include/python3.10/pyconfig.h
    - test :
        - /usr/lib/python3.10/test
    - tkinter :
        - /usr/lib64/python3.10/lib-dynload/_tkinter.cpython-310-x86_64-linux-gnu.so*
setup      : |
    %apply_patches

    %configure --enable-ipv6=yes \
               --enable-loadable-sqlite-extensions \
               --enable-optimizations \
               --enable-shared \
               --with-ensurepip=install \
               --with-lto \
               --with-system-expat \
               --with-system-ffi \
               --without-cxx-main \
               ax_cv_c_float_words_bigendian=no \
               CFLAGS="$CFLAGS -I/usr/include"
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 Tools/gdb/libpython.py $installdir/usr/share/gdb/auto-load/usr/lib64/libpython3.10.so.1.0-gdb.py
    rm $installdir/usr/bin/2to3
