name       : python3
version    : 3.9.7
release    : 38
source     :
    - https://www.python.org/ftp/python/3.9.7/Python-3.9.7.tar.xz : f8145616e68c00041d1a6399b76387390388f8359581abc24432bb969b5e3c57
license    : Python-2.0
summary    :
    - Python development environment - 3.9
    - test : Python 3.9 Test package
component  :
    - programming.python
    - test : programming.python
    - tkinter : programming.python
description: |
    The Python 3 package contains the Python development environment. This is useful for object-oriented programming, writing scripts, prototyping large programs or developing entire applications.
optimize   :
    - speed
networking : yes
builddeps  :
    - pkgconfig(harfbuzz) # Fix linking for tkinter
    - pkgconfig(libffi)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - bzip2-devel
    - db5-devel
    - gdbm-devel
replaces   :
    - python3-setuptools
rundeps    :
    - test : python3
    - tkinter : python3
patterns   :
    - /usr/include/python3.9/pyconfig.h
    - test :
        - /usr/lib/python3.9/test
    - tkinter :
        - /usr/lib64/python3.9/lib-dynload/_tkinter.cpython-39-x86_64-linux-gnu.so*
setup      : |
    %apply_patches

    %configure --enable-ipv6=yes \
               --enable-loadable-sqlite-extensions \
               --enable-optimizations \
               --enable-shared \
               --with-ensurepip=install \
               --with-system-expat \
               --with-system-ffi \
               --without-cxx-main \
               CFLAGS="$CFLAGS -I/usr/include"
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/bin/2to3
