name       : python3
version    : 3.5.4
release    : 13
source     :
    - https://www.python.org/ftp/python/3.5.4/Python-3.5.4.tar.xz : 94d93bfabb3b109f8a10365a325f920f9ec98c6e2380bf228f9700a14054c84c
license    :
    - Python-2.0
summary    :
    - Python development environment - 3.5
    - test : Python 3.5 Test package
component  :
    - programming.python
    - test : programming.python
    - tkinter : programming.python
description: |
    The Python 3 package contains the Python development environment. This is useful for object-oriented programming, writing scripts, prototyping large programs or developing entire applications.
builddeps  :
    - pkgconfig(harfbuzz) # Fix linking for tkinter
    - pkgconfig(zlib)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(libffi)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - bzip2-devel
    - db5-devel
    - gdbm-devel
replaces   :
    - python3-setuptools
rundeps    :
    - test : python3
    - tkinter : python3
patterns   :
    - /usr/include/python3.5m/pyconfig.h
    - test :
        - /usr/lib/python3.5/test
    - tkinter :
        - /usr/lib64/python3.5/lib-dynload/_tkinter.cpython-35m-x86_64-linux-gnu.so
setup      : |
    %patch -p1 < $pkgfiles/0001-ensurepip-Always-install-pip-setuptools-ignoring-ins.patch

    %configure --prefix=/usr \
               --enable-shared \
               --with-system-expat \
               --with-system-ffi \
               --with-threads \
               --with-ensurepip=install \
               --without-cxx-main \
               --with-signal-module \
               --enable-ipv6=yes \
               CFLAGS="$CFLAGS -I/usr/include"
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/bin/2to3
