name        : python3
version     : 3.5.1
release     : 10
source     :
    - https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz : c6d57c0c366d9060ab6c0cdf889ebf3d92711d466cc0119c441dbf2746f725c9
license     :
    - Python-2.0
summary     :
    - Python development environment - 3.5
    - test: Python 3.5 Test package
component   :
    - programming.python
    - test: programming.python
description : |
    The Python 3 package contains the Python development environment. This is useful for object-oriented programming, writing scripts, prototyping large programs or developing entire applications.
builddeps  :
    - pkgconfig(zlib)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(libffi)
    - db5-devel
replaces   :
    - python3-setuptools
rundeps    :
    - test:
        - python3
patterns   :
    - test:
        - /usr/lib/python3.5/test
setup      : |
    if [[ -e /usr/lib/python3.5/ ]]; then
        rm -rf /usr/lib/python3.5
    fi
    %configure --prefix=/usr \
               --enable-shared \
               --with-system-expat \
               --with-system-ffi \
               --with-threads \
               --with-ensurepip=install \
               --without-cxx-main \
               --with-signal-module \
               --enable-ipv6=yes
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/bin/2to3
