name       : python3
version    : 3.6.5
release    : 18
source     :
    - https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tar.xz : f434053ba1b5c8a5cc597e966ead3c5143012af827fd3f0697d21450bb8d87a6
license    :
    - Python-2.0
summary    :
    - Python development environment - 3.6
    - test : Python 3.6 Test package
component  :
    - programming.python
    - test : programming.python
    - tkinter : programming.python
description: |
    The Python 3 package contains the Python development environment. This is useful for object-oriented programming, writing scripts, prototyping large programs or developing entire applications.
builddeps  :
    - pkgconfig(harfbuzz) # Fix linking for tkinter
    - pkgconfig(zlib)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(libffi)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - bzip2-devel
    - db5-devel
    - gdbm-devel
replaces   :
    - python3-setuptools
rundeps    :
    - test : python3
    - tkinter : python3
patterns   :
    - /usr/include/python3.6m/pyconfig.h
    - test :
        - /usr/lib/python3.6/test
    - tkinter :
        - /usr/lib64/python3.6/lib-dynload/_tkinter.cpython-36m-x86_64-linux-gnu.so
setup      : |
    %patch -p1 < $pkgfiles/0001-ensurepip-Always-install-pip-setuptools-ignoring-ins.patch

    %configure --prefix=/usr \
               --enable-shared \
               --with-system-expat \
               --with-system-ffi \
               --with-threads \
               --with-ensurepip=install \
               --without-cxx-main \
               --with-signal-module \
               --enable-ipv6=yes \
               --enable-loadable-sqlite-extensions \
               CFLAGS="$CFLAGS -I/usr/include"
build      : |
    %make profile-opt
install    : |
    %make_install
    rm $installdir/usr/bin/2to3
